name: Remote Deployment via Self-Hosted Lab

on:
  push:
    branches: [ main ]

jobs:
  local-deploy-test:
    name: 🚀 Local Execution via Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🏗️ Execute Command Locally
        run: |
          echo "Successfully running inside my own Ubuntu VM! 🎉"
          cd ~
          mkdir -p remote-deployed-app
          ls -ld remote-deployed-app
          echo "Dynamic Folder Created at $(date)"
